### ISSUE TITLE
inotify-tools

### ISSUE THREAD

**Issue by otteydw** [djjudas21/puppet-ossec#13]
There seems to be an (undocumented) dependency within ossec-hids package for the inotify-tools package.  On RHEL systems, this requires access to the EPEL repo.

Not sure how you could handle this inside of this module, but it would be helpful if any such dependencies would be documented on the site.

**Comment by djjudas21** [comment]
Interesting. All my systems have EPEL installed by default so I never noticed this.

I think the best way to proceed would be to make this module depend on `stahnma/epel` and then have the `ossec-hids` package require that the `epel` class is present. Should be quite an easy fix; leave it with me!

**Comment by djjudas21** [comment]
Right... can you have a look at 2056487 and let me know if this fixes the problem. If it does, I'll push a new release to Puppet Forge too.

**Comment by otteydw** [comment]
Well, I'll be honest that I'm not super-savvy with github.  I looked at the code changes and the syntax looks correct to me puppet-wise.

**Comment by djjudas21** [comment]
Yeah, fair enough. I know everyone who uses Puppet modules does so in a different way. I've just released [v1.4.0](https://forge.puppetlabs.com/jgazeley/ossec) of this module and published it on the Forge. Hopefully it will fix your problem - open a new issue if not.

Cheers,
Jonathan
