### ISSUE TITLE
Restart of ossec from puppet fails due to ossec init scripts returns wrong exit code on ubuntu 14.04.

### ISSUE THREAD

**Issue by enemarke** [djjudas21/puppet-ossec#15]
Running ubuntu 14.04 both init scripts (ossec-hids-(server|agent)) return exit code 0 on status when the service is not running. This makes the puppet service in client.pp to  always see the services as running and no restart is executes when ossec service crashes.
Changing hasstatus to false should fix the problem.

**Comment by djjudas21** [comment]
Fixed in 8ce1dcb058d8a2fa5275dad77651f0217408bd34

**Comment by djjudas21** [comment]
BTW, sorry this took so long!
