### ISSUE TITLE
Module metadata - slash in name broke R10K

### ISSUE THREAD

**Issue by VAdamec** [djjudas21/puppet-ossec#21]
"name": "jgazeley/ossec",

==> master: ERROR	 -> Invalid 'name' field in metadata.json: the namespace contains non-alphanumeric characters

can you fix it ? use dash

**Comment by djjudas21** [comment]
Thanks for reporting. This is confusing and inconsistent behaviour. It seems the module name must contain a dash to work with r10k, but the dependencies must contain a slash to work with the Puppet module tool.

I've changed the name of the module in db4acfa and I'll do a release shortly.
