### ISSUE TITLE
var_ossec_etc_client.keys_${agent_ip_address}_part has the potential to not be unique 

### ISSUE THREAD

**Issue by SyBernot** [djjudas21/puppet-ossec#22]
I already hit this wall and you get a very unhelpful error message on the ossec server

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Concat::Fragment[var_ossec_etc_client.keys_10.10.16.56_part] is already declared in file /etc/puppet/environments/prod/modules/ossec/manifests/agentkey.pp:17; cannot redeclare at /etc/puppet/environments/prod/modules/ossec/manifests/agentkey.pp:17 on node ossec-server.example.com`

We reinstalled a system with the same IP but a different name and suddenly we had the dupe definition

If someone should come looking for that message the fix is to run 
`puppet node deactivate oldname.example.com`
on the puppet master to clear out the entry in puppetdb

Looking over the Puppet docs for exported refs they recommend the following

>To ensure uniqueness, every resource you export should include a substring unique to the node exporting it into its title and name/namevar. The most expedient way is to use the hostname or fqdn facts.

So unless there is some compelling reason to use agent_ip_adress it should probably be changed to agent_name.

**Comment by djjudas21** [comment]
I think you're right, it would be better to use `$agent_name` to key the `concat::fragment` and would avoid the situation you've described.

However I should add that doing `puppet node deactivate` really should be standard practice every time you decommission on a server. You can also set PuppetDB to [auto deactivate nodes that haven't checked in for a certain time](https://docs.puppetlabs.com/puppetdb/latest/configure.html#node-ttl).

**Comment by djjudas21** [comment]
I've pushed a light-touch fix in a0563a1. It still uses `$agent_ip_address` in most places and only uses `$agent_name` to distinguish the `concat::fragment`. This should avoid your problem without causing all the agents to regenerate their keys.
