### ISSUE TITLE
Atomic Repository GPG Key Changed

### ISSUE THREAD

**Issue by sedlund** [djjudas21/puppet-ossec#30]
https://www.atomicorp.com/RPM-GPG-KEY.atomicorp.txt

**Comment by djjudas21** [comment]
Sigh. They've done this before and broken RPM updates for many users with no notice. I'll push a fix, bear with me...

**Comment by djjudas21** [comment]
Fixed in #31

**Comment by djjudas21** [comment]
Also packaged this as 1.8.1 on [Puppet Forge](https://forge.puppetlabs.com/jgazeley/ossec/readme)
