### ISSUE TITLE
RHEL / Centos 7 Atomic Repo mirrorlist broken

### ISSUE THREAD

**Issue by sedlund** [djjudas21/puppet-ossec#32]
mirrorlist => 'http://updates.atomicorp.com/channels/mirrorlist/ossec/centos-$releasever-$basearch',

On RHEL 7 expands to:

http://updates.atomicorp.com/channels/mirrorlist/ossec/centos-7Server-x86_64

As expected.   Unfortunately Atomic repo has their mirror list here:

http://updates.atomicorp.com/channels/mirrorlist/ossec/centos-7-x86_64

I've tweeted to @atomicorp : https://twitter.com/sredlund/status/659376449779036160 to have them fix.

**Comment by djjudas21** [comment]
Well spotted, thanks for reporting. If you don't get anywhere with Atomicorp, let me know and I'll work around it in the code.

**Comment by djjudas21** [comment]
@sedlund Does this commit fix the issue for you? Happy to push it out if it does.

**Comment by djjudas21** [comment]
Well, I merged it to `master` anyway because even when they put the symlink in as you suggested, it won't stop the original path from working.

**Comment by sedlund** [comment]
Sorry for my lateness.   Yes, I sent an email and they added the symlink.  I think all is well now.

Thanks
