### ISSUE TITLE
Change template to allow multiple email_to addresses

### ISSUE THREAD

**Issue by paul-cs** [djjudas21/puppet-ossec#41]
I need to be able to specify multiple email addresses to send the notifications to. The easiest way to do this would be to change the ossec_emailto variable to an array. If you are happy with this, then in the template 10_ossec.conf.erb, line 4, just needs to be changed to:

<% @ossec_emailto.each do |emailto| -%>
	<email_to><%= emailto %></email_to>
<% end -%>

**Comment by djjudas21** [comment]
Thanks. Can you take a look at 771a45e and see if it looks OK? I had to tweak your code and add in the `<email_to>` tags and I also mashed it all onto one line.

**Comment by paul-cs** [comment]
Yip, that is what I pasted into this editor originally, I didn't notice that something in this editor removed the email_to tags. It must have treated it as html or something.... :-)

**Comment by djjudas21** [comment]
Cool. Can you confirm that this commit is working in your environment, and when we've got a positive result I'll merge this to `master`.

**Comment by paul-cs** [comment]
That works, but I would recommend that you remove the last '-' from the end tag, other wise you get no newlines and it makes the config look ugly.

**Comment by djjudas21** [comment]
Fixed in #44
