### ISSUE TITLE
New Forge release

### ISSUE THREAD

**Issue by coreone** [djjudas21/puppet-ossec#47]
Hello,

I put in some PRs, but they are not yet available as a tagged release in PuppetForge yet.  Would there be any change that you could release a new version to the Forge so that I can refer to it by tag as opposed to commit hash?

Thanks!

**Comment by djjudas21** [comment]
Hey, sorry I didn't realise that the latest goodies weren't in a tagged release. I'm on my phone at the moment but when I get to my space I'll tag a release and upload it to Puppet Forge too :)

**Comment by djjudas21** [comment]
Space = PC, damn autocorrect!

**Comment by djjudas21** [comment]
OK, I've tagged release `1.11.0` which is available on Github and on Puppet Forge. Thanks for your contributions.

Just a side point, this module has been forked as `wazuh/ossec` which seems to be attracting more development effort than my ossec module. I haven't used `wazuh/ossec` yet, but you might consider trying it. If enough people prefer it, I may well decide to drop support for this module and tell people to use `wazuh` instead.
