### ISSUE TITLE
Agent unable to call authd

### ISSUE THREAD

**Issue by paul-cs** [djjudas21/puppet-ossec#49]
Hi Jonathon, 

I've just upgraded to 1.11.0 of ossec. When I try and run the agent, I'm wanting it to execute agent-auth (ln 84). However, the if statement is keyed to only check if $::uniqueid (ln 65) is defined. I cannot see for the life of me how uniqueid is getting set in the ossec namespace, or how I can override it to make the agent-auth execute. Maybe I'm missing something. Can you please let me know? Thanks

**Comment by djjudas21** [comment]
Hi,

`$::uniqueid` is a built-in fact in Facter. I'm not quite sure what's going on - some users have reported that their distributions of Facter don't have `uniqueid` and have `uuid` instead. I've never seen `uuid` and all my Facter installations (CentOS 6, 7 and Fedora 23) have `uniqueid`. I wonder if this is distribution policy - which OS are you running?

Thanks,
Jonathan

**Comment by djjudas21** [comment]
I just tried on Ubuntu 15.10 and that only has `uniqueid` too. All the Facters I've tried have been 2.4.4, 2.4.2 or 2.3.0. This might be a change with Facter 3.0 - can you check your Facter version too, please?

**Comment by djjudas21** [comment]
Ruh, I just upgraded one of my CentOS 7 machines to Facter 3.1.5 and It has neither `uniqueid` nor `uuid`

**Comment by paul-cs** [comment]
Hi Jonathan,

I'm on centos 7, but my facter version is only 2.4.6. I want to force it to
call agent-auth, not make its own client.key. Its obviously getting a
uniqueid fine as I can see it in the generated key. Sorry if I wasn't clear
in the first message. I'm wanting a way to force it to call agent-auth.

On Wed, Mar 30, 2016 at 7:51 PM, Jonathan <notifications@github.com> wrote:

> Ruh, I just upgraded one of my CentOS 7 machines to Facter 3.1.5 and It
> has neither uniqueid nor uuid
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/djjudas21/puppet-ossec/issues/49#issuecomment-203328376>
>



-- 

*Paul Edwards*

Principal Consultant


☎ +61 4 20913987
✉ paul.edwards@contextspace.com
✎ level 5 | 95 Pitt Street | Sydney, NSW 2000 | Australia
<https://maps.google.com.au/maps?q=Level+5+%7C+95+Pitt+Street+%7C+Sydney,+NSW+2000+%7C+Australia&hl=en&sll=-33.796924,150.922433&sspn=1.540639,3.348083&hnear=5%2F95+Pitt+St,+New+South+Wales+2000&t=m&z=16>
☛ www.contextspace.com

**Comment by djjudas21** [comment]
Hmm OK. I'll be honest, I haven't actually touched this code for ages as I no longer use it. Several other contributors have added features over recent months, including this one. This probably will need a code change to add in a parameter etc.

**Comment by djjudas21** [comment]
I should also add that my module has been forked into https://forge.puppetlabs.com/wazuh/ossec and there are many improvements while mostly retaining compatibility. You might want to give that a go.

**Comment by paul-cs** [comment]
your correct, it has been fixed is wazuh's version. Thanks for that.

On Wed, Mar 30, 2016 at 9:41 PM, Jonathan <notifications@github.com> wrote:

> I should also add that my module has been forked into
> https://forge.puppetlabs.com/wazuh/ossec and there are many improvements
> while mostly retaining compatibility. You might want to give that a go.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/djjudas21/puppet-ossec/issues/49#issuecomment-203374068>
>



-- 

*Paul Edwards*

Principal Consultant


☎ +61 4 20913987
✉ paul.edwards@contextspace.com
✎ level 5 | 95 Pitt Street | Sydney, NSW 2000 | Australia
<https://maps.google.com.au/maps?q=Level+5+%7C+95+Pitt+Street+%7C+Sydney,+NSW+2000+%7C+Australia&hl=en&sll=-33.796924,150.922433&sspn=1.540639,3.348083&hnear=5%2F95+Pitt+St,+New+South+Wales+2000&t=m&z=16>
☛ www.contextspace.com

**Comment by djjudas21** [comment]
Cool - I'm glad you found a fix. I should probably take my module down now that no longer offers any advantage over `wazuh/ossec`.
